name: Generate Readme Stats Images

on:
  schedule:
    - cron: "0 6 * * *"   # roda 1x por dia, 06:00 UTC (~03:00 Brasília)
  workflow_dispatch:        # permite rodar manualmente pela aba Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate stats images
    steps:
      - name: Generate images
        uses: jstrieb/github-stats@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
